apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-api
  namespace: personal-api
spec:
  selector:
    matchLabels:
      app: personal-api
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: personal-api
    spec:
      containers:
      - name: personal-api
        image: kokuzo.tailc38f.ts.net/personal-api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        args:
        - "/config/config.toml"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        secret: 
          secretName: personal-api-secrets-file
          items:
          - key: config.toml
            path: config.toml
