apiVersion: v1
kind: Service
metadata:
  name: personal-api-service
  namespace: personal-api
spec:
  selector:
    app: personal-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
