// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordEmoji = { "Official": { name: string, } } | { "Unofficial": { name: string, id: bigint, animated: boolean, url: string, } } | { "Unknown": { name: string, id: bigint | null, animated: boolean | null, } };
