// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordCustomStatus } from "./DiscordCustomStatus";
import type { DiscordOnlineStatus } from "./DiscordOnlineStatus";

export type DiscordUserInfo = { display_name: string, status: DiscordOnlineStatus, client_status: DiscordOnlineStatus | null, custom_status: DiscordCustomStatus | null, };
