// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LastFmImageSet = { small: string | null, medium: string | null, large: string | null, extralarge: string | null, };
