// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastFmTrack } from "./LastFmTrack";

export type LastFmUserInfo = { username: string, currently_playing: LastFmTrack | null, };
