// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastFmArtist } from "./LastFmArtist";
import type { LastFmImageSet } from "./LastFmImageSet";

export type LastFmTrack = { artist: LastFmArtist, name: string, image: LastFmImageSet, album: string, url: string, date: string, };
