// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SteamGameInfo } from "./SteamGameInfo";

export type SteamUserInfo = { steam_id: string, persona_name: string, game: SteamGameInfo | null, };
