// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordUserInfo } from "./DiscordUserInfo";
import type { LastFmUserInfo } from "./LastFmUserInfo";
import type { MinimalUser } from "./MinimalUser";
import type { SteamUserInfo } from "./SteamUserInfo";

export type User = { name: string, owners: Array<MinimalUser>, aliases: Array<string>, pronouns: Array<string>, time_zone: string, discord: DiscordUserInfo | null, last_fm: LastFmUserInfo | null, steam: SteamUserInfo | null, };
